### ISSUE TITLE
Structural Organization

### ISSUE THREAD

**Issue by ofonimefrancis** [DesmondANIMUS/Conduit_2#1]
1. Since this application is going to be consumed by a mobile application, it is best to structure the API in a manner that the JSON returned is detailed about the particular data being consumed.

2. The application structure, should consist of sub packages with a specific purpose for example model - to handle all the models needed by the API, config- Configuration options etc

I will create a PR with some changes made to the Structure of the repo

**Comment by gaurav-gogia** [comment]
I thought I did make those changes, by putting data models in models file and routes in routes file and so on. But....okay then, will see your approach when you send PR
